default:
	@just --list

dev:
	gleam run -m lustre/dev start

build:
	gleam run -m lustre/dev build app --outdir=../server/priv/static

build-min:
	gleam run -m lustre/dev build app --minify --outdir=../server/priv/static
