default:
	@just --list

dev:
	gleam run -m lustre/dev start

build-dev:
	gleam run -m lustre/dev build --outdir=../server/priv/static

build-prod:
	gleam run -m lustre/dev build --minify --outdir=../server/priv/static
