default:
	@just --list

env:
	export $(grep -v '^#' .env | xargs)

squirrel: env
	gleam run -m squirrel
run: env squirrel
	gleam run

migrate: env
    dbmate migrate
up: env
    dbmate up
down: env
    dbmate down
