default:
	@just --list

squirrel:
	gleam run -m squirrel

run: squirrel
	gleam run

watch: squirrel
	watchexec --restart --verbose --wrap-process=session --stop-signal SIGTERM --exts gleam --debounce 500ms --watch src/ -- "gleam run"

migrate:
    dbmate migrate

up:
    dbmate up

down:
    dbmate down
